version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bcommerce-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1q2w3e4r@#$"
      POSTGRES_DB: bcommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bcommerce-network

volumes:
  pgdata:

networks:
  bcommerce-network:
    driver: bridge
